package com.tplink.cartoon.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tplink.cartoon.data.bean.Comic;

import com.tplink.cartoon.greendao.ComicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicDaoConfig;

    private final ComicDao comicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        comicDao = new ComicDao(comicDaoConfig, this);

        registerDao(Comic.class, comicDao);
    }
    
    public void clear() {
        comicDaoConfig.clearIdentityScope();
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

}
