package com.tplink.cartoon.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tplink.cartoon.data.bean.Comic;
import com.tplink.cartoon.data.bean.DBSearchResult;
import com.tplink.cartoon.data.bean.DBDownloadItem;

import com.tplink.cartoon.greendao.ComicDao;
import com.tplink.cartoon.greendao.DBSearchResultDao;
import com.tplink.cartoon.greendao.DBDownloadItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comicDaoConfig;
    private final DaoConfig dBSearchResultDaoConfig;
    private final DaoConfig dBDownloadItemDaoConfig;

    private final ComicDao comicDao;
    private final DBSearchResultDao dBSearchResultDao;
    private final DBDownloadItemDao dBDownloadItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        dBSearchResultDaoConfig = daoConfigMap.get(DBSearchResultDao.class).clone();
        dBSearchResultDaoConfig.initIdentityScope(type);

        dBDownloadItemDaoConfig = daoConfigMap.get(DBDownloadItemDao.class).clone();
        dBDownloadItemDaoConfig.initIdentityScope(type);

        comicDao = new ComicDao(comicDaoConfig, this);
        dBSearchResultDao = new DBSearchResultDao(dBSearchResultDaoConfig, this);
        dBDownloadItemDao = new DBDownloadItemDao(dBDownloadItemDaoConfig, this);

        registerDao(Comic.class, comicDao);
        registerDao(DBSearchResult.class, dBSearchResultDao);
        registerDao(DBDownloadItem.class, dBDownloadItemDao);
    }
    
    public void clear() {
        comicDaoConfig.clearIdentityScope();
        dBSearchResultDaoConfig.clearIdentityScope();
        dBDownloadItemDaoConfig.clearIdentityScope();
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

    public DBSearchResultDao getDBSearchResultDao() {
        return dBSearchResultDao;
    }

    public DBDownloadItemDao getDBDownloadItemDao() {
        return dBDownloadItemDao;
    }

}
